### ISSUE TITLE
Star-search (*) results in error message

### ISSUE THREAD

**Issue by johnnovak** [alaviss/nim.nvim#43] opened 2021-06-06 00:07 UTC
Pressing star (*) anywhere in a Nim file to search for the symbol nearest to the cursor results in an error 100% of the time:

![image](https://user-images.githubusercontent.com/698770/120908550-acc2f880-c6ae-11eb-8681-41bf740ec19d.png)

**Comment by alaviss** [comment] 2021-06-09 14:53
This is weird, how did you install `nim.nvim`?

**Comment by johnnovak** [comment] 2021-06-10 05:13
Using Packer.
https://github.com/wbthomason/packer.nvim 

I uninstalled/reinstalled it a few times, same results.

**Comment by alaviss** [comment] 2021-06-10 05:41
Did you install nim.nvim with `opt = true`?

And what is your neovim version?

**Comment by johnnovak** [comment] 2021-06-11 06:24
No I didn't use opt=true. I use the latest 0.5.x nightly build from a few weeks ago.

**Comment by alaviss** [comment] 2021-06-11 18:10
Unfortunately I can not reproduce this with the following configuration:

`lua/plugins.lua`:

```lua
-- This file can be loaded by calling `lua require('plugins')` from your init.vim

-- Only required if you have packer configured as `opt`
vim.cmd [[packadd packer.nvim]]
-- Only if your version of Neovim doesn't have https://github.com/neovim/neovim/pull/12632 merged
-- vim._update_package_paths()

return require('packer').startup(function()
  -- Packer can manage itself
  use 'wbthomason/packer.nvim'

  -- Simple plugins can be specified as strings
  use 'alaviss/nim.nvim'
end)
```

`init.vim`:

```vimscript
lua require('plugins')
```

This is on a blank profile. Can you share your configuation with me?

**Comment by johnnovak** [comment] 2021-06-11 23:28
Ok, sorry man, now I tried removing and reinstalling it again, and now it works fine... I must have screwed something up. I was experimenting with other Nim plugins as well, maybe your interacted with some remnants of those...

So please close this, user error.

On a related note, this is a cool project, but because of the general unreliability of nimsuggest I can't use the LSP based stuff because nimsuggest just dies when navigating around my medium sized project that contains a fair bit of macros. It's not your fault, I know. However, it would useful to introduce some global config parameters to be able to toggle parts of the plugin (e.g. I'd like to disable LSP because it's virtually useless for me, and just enable the parts that can work without the LSP, e.g. regexp based syntax highlighting, the asterisk search improvement, etc).

**Comment by alaviss** [comment] 2021-06-12 20:55
> However, it would be useful to introduce some global config parameters to be able to toggle parts of the plugin (e.g. I'd like to disable LSP because it's virtually useless for me, and just enable the parts that can work without LSP, e.g. regexp based syntax highlighting, the asterisk search improvement, etc).

There are some configs but there are none to disable nimsuggest yet. One of the main issues is that I designed the plugin to depend on nimsuggest for the bulk of the highlighting, so disabling nimsuggest may cripple the usability of the plugin a tad too much. But I will consider it.

I'm gonna close this issue since this it is solved.

**Closed by alaviss** 2021-06-12 20:55 UTC
Labels: bug
